//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------
#include "pch.h"

#if defined _DEBUG && !defined DISABLE_XAML_GENERATED_BINDING_DEBUG_OUTPUT
extern "C" __declspec(dllimport) int __stdcall IsDebuggerPresent();
#endif

#include "Editor.xaml.h"

void ::ARCC::Editor::InitializeComponent()
{
    if (_contentLoaded)
    {
        return;
    }
    _contentLoaded = true;
    ::Windows::Foundation::Uri^ resourceLocator = ref new ::Windows::Foundation::Uri(L"ms-appx:///Editor.xaml");
    ::Windows::UI::Xaml::Application::LoadComponent(this, resourceLocator, ::Windows::UI::Xaml::Controls::Primitives::ComponentResourceLocation::Application);
}

void ::ARCC::Editor::Connect(int __connectionId, ::Platform::Object^ __target)
{
    switch (__connectionId)
    {
        case 1:
            {
                this->globalStack = safe_cast<::Windows::UI::Xaml::Controls::StackPanel^>(__target);
            }
            break;
        case 2:
            {
                this->stackPanel = safe_cast<::Windows::UI::Xaml::Controls::StackPanel^>(__target);
            }
            break;
        case 3:
            {
                this->script = safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(__target);
            }
            break;
        case 4:
            {
                this->topBar = safe_cast<::Windows::UI::Xaml::Controls::RelativePanel^>(__target);
            }
            break;
        case 5:
            {
                this->button = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::ARCC::Editor::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&Editor::button_Click);
            }
            break;
        case 6:
            {
                this->reload = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->reload))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::ARCC::Editor::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&Editor::dynamicRealloc);
            }
            break;
        case 7:
            {
                this->width = safe_cast<::Windows::UI::Xaml::Controls::ComboBox^>(__target);
            }
            break;
        case 8:
            {
                this->generate = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->generate))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::ARCC::Editor::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&Editor::setGen);
            }
            break;
        case 9:
            {
                this->Load = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->Load))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::ARCC::Editor::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&Editor::loadIx);
            }
            break;
    }
    _contentLoaded = true;
}

::Windows::UI::Xaml::Markup::IComponentConnector^ ::ARCC::Editor::GetBindingConnector(int __connectionId, ::Platform::Object^ __target)
{
    __connectionId;         // unreferenced
    __target;               // unreferenced
    return nullptr;
}


