#pragma once
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------


namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Controls {
                ref class SplitView;
                ref class Button;
                ref class CommandBar;
                ref class Frame;
            }
        }
    }
}
namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Shapes {
                ref class Rectangle;
            }
        }
    }
}

namespace ARCC
{
    [::Windows::Foundation::Metadata::WebHostHidden]
    partial ref class MainPage : public ::Windows::UI::Xaml::Controls::Page, 
        public ::Windows::UI::Xaml::Markup::IComponentConnector,
        public ::Windows::UI::Xaml::Markup::IComponentConnector2
    {
    public:
        void InitializeComponent();
        virtual void Connect(int connectionId, ::Platform::Object^ target);
        virtual ::Windows::UI::Xaml::Markup::IComponentConnector^ GetBindingConnector(int connectionId, ::Platform::Object^ target);
    
    private:
        bool _contentLoaded;
    
        private: ::Windows::UI::Xaml::Controls::SplitView^ spv;
        private: ::Windows::UI::Xaml::Controls::Button^ settings;
        private: ::Windows::UI::Xaml::Controls::Button^ HamburgerButton;
        private: ::Windows::UI::Xaml::Controls::Button^ MenuButton4;
        private: ::Windows::UI::Xaml::Controls::Button^ MenuButton3;
        private: ::Windows::UI::Xaml::Controls::Button^ MenuButton2;
        private: ::Windows::UI::Xaml::Controls::Button^ MenuButton1;
        private: ::Windows::UI::Xaml::Controls::CommandBar^ Cbar;
        private: ::Windows::UI::Xaml::Controls::Frame^ LaFrame;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ Lbar;
    };
}

