//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------
#include "pch.h"

#if defined _DEBUG && !defined DISABLE_XAML_GENERATED_BINDING_DEBUG_OUTPUT
extern "C" __declspec(dllimport) int __stdcall IsDebuggerPresent();
#endif

#include "MainPage.xaml.h"

void ::ARCC::MainPage::InitializeComponent()
{
    if (_contentLoaded)
    {
        return;
    }
    _contentLoaded = true;
    ::Windows::Foundation::Uri^ resourceLocator = ref new ::Windows::Foundation::Uri(L"ms-appx:///MainPage.xaml");
    ::Windows::UI::Xaml::Application::LoadComponent(this, resourceLocator, ::Windows::UI::Xaml::Controls::Primitives::ComponentResourceLocation::Application);
}

void ::ARCC::MainPage::Connect(int __connectionId, ::Platform::Object^ __target)
{
    switch (__connectionId)
    {
        case 1:
            {
                this->rootPivot = safe_cast<::Windows::UI::Xaml::Controls::Pivot^>(__target);
            }
            break;
        case 2:
            {
                this->helpFrame = safe_cast<::Windows::UI::Xaml::Controls::Frame^>(__target);
            }
            break;
        case 3:
            {
                this->helpStack = safe_cast<::Windows::UI::Xaml::Controls::RelativePanel^>(__target);
            }
            break;
        case 4:
            {
                this->tb1 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
            }
            break;
        case 5:
            {
                this->console = safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(__target);
            }
            break;
        case 6:
            {
                this->simFrame = safe_cast<::Windows::UI::Xaml::Controls::Frame^>(__target);
            }
            break;
        case 7:
            {
                this->insFrame = safe_cast<::Windows::UI::Xaml::Controls::Frame^>(__target);
            }
            break;
        case 8:
            {
                this->globalStack = safe_cast<::Windows::UI::Xaml::Controls::StackPanel^>(__target);
            }
            break;
        case 9:
            {
                this->stackPanel = safe_cast<::Windows::UI::Xaml::Controls::StackPanel^>(__target);
            }
            break;
        case 10:
            {
                this->script = safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(__target);
            }
            break;
        case 11:
            {
                this->topBar = safe_cast<::Windows::UI::Xaml::Controls::RelativePanel^>(__target);
            }
            break;
        case 12:
            {
                this->button = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::ARCC::MainPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::button_Click);
            }
            break;
        case 13:
            {
                this->reload = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->reload))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::ARCC::MainPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::dynamicRealloc);
            }
            break;
        case 14:
            {
                this->width = safe_cast<::Windows::UI::Xaml::Controls::ComboBox^>(__target);
            }
            break;
        case 15:
            {
                this->generate = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->generate))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::ARCC::MainPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::setGen);
            }
            break;
        case 16:
            {
                this->Load = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->Load))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::ARCC::MainPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::loadIx);
            }
            break;
        case 17:
            {
                this->asmFrame = safe_cast<::Windows::UI::Xaml::Controls::Frame^>(__target);
            }
            break;
        case 18:
            {
                this->boqqq = safe_cast<::Windows::UI::Xaml::Controls::RelativePanel^>(__target);
            }
            break;
        case 19:
            {
                this->Tools = safe_cast<::Windows::UI::Xaml::Controls::RelativePanel^>(__target);
            }
            break;
        case 20:
            {
                this->in = safe_cast<::Windows::UI::Xaml::Controls::ScrollViewer^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::ScrollViewer^>(this->in))->ViewChanged += ref new ::Windows::Foundation::EventHandler<::Windows::UI::Xaml::Controls::ScrollViewerViewChangedEventArgs^>(this, (void (::ARCC::MainPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Controls::ScrollViewerViewChangedEventArgs^))&MainPage::VC);
            }
            break;
        case 21:
            {
                this->LineNo = safe_cast<::Windows::UI::Xaml::Controls::ScrollViewer^>(__target);
            }
            break;
        case 22:
            {
                this->out = safe_cast<::Windows::UI::Xaml::Controls::ScrollViewer^>(__target);
            }
            break;
        case 23:
            {
                this->outT = safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(__target);
            }
            break;
        case 24:
            {
                this->LineNoT = safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(__target);
            }
            break;
        case 25:
            {
                this->inT = safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(__target);
            }
            break;
        case 26:
            {
                this->ASSLoad = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->ASSLoad))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::ARCC::MainPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::OpenAsmFile);
            }
            break;
        case 27:
            {
                this->ASSsave = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->ASSsave))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::ARCC::MainPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::SaveASM);
            }
            break;
        case 28:
            {
                this->ISLoad = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->ISLoad))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::ARCC::MainPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::LoadIS);
            }
            break;
        case 29:
            {
                this->Len = safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(__target);
            }
            break;
        case 30:
            {
                this->fX = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
            }
            break;
        case 31:
            {
                this->ASGen = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->ASGen))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::ARCC::MainPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::generateMC);
            }
            break;
        case 32:
            {
                this->MIF = safe_cast<::Windows::UI::Xaml::Controls::CheckBox^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::CheckBox^>(this->MIF))->Checked += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::ARCC::MainPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::Mcheck);
                (safe_cast<::Windows::UI::Xaml::Controls::CheckBox^>(this->MIF))->Unchecked += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::ARCC::MainPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::MUcheck);
            }
            break;
        case 33:
            {
                this->BIN = safe_cast<::Windows::UI::Xaml::Controls::CheckBox^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::CheckBox^>(this->BIN))->Checked += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::ARCC::MainPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::Bcheck);
                (safe_cast<::Windows::UI::Xaml::Controls::CheckBox^>(this->BIN))->Unchecked += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::ARCC::MainPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::BUcheck);
            }
            break;
    }
    _contentLoaded = true;
}

::Windows::UI::Xaml::Markup::IComponentConnector^ ::ARCC::MainPage::GetBindingConnector(int __connectionId, ::Platform::Object^ __target)
{
    __connectionId;         // unreferenced
    __target;               // unreferenced
    return nullptr;
}


